version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: |
        echo "
        try { 
          rs.status(); 
          print('Replica set already initialized'); 
        } catch (err) { 
          print('Initializing replica set...'); 
          rs.initiate(); 
          print('Replica set initialized'); 
        }
        " | mongosh --port 27017 --quiet
      interval: 10s
      timeout: 10s
      start_period: 20s
      retries: 5

  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongo:27017/git_actions_db?replicaSet=rs0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/webhook"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--config"
      - "/etc/ngrok.yml"
      - "--all"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040/api/tunnels"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
