version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    command: ["mongod", "--replSet", "rs0"]
    volumes:
      - ./mongo-data:/data/db
  
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/git_actions_db

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--config"
      - "/etc/ngrok.yml"
      - "--all"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
